server:
  port: 8080

spring:
  application:
    name: utils
  jackson:
    default-property-inclusion: non_null
    time-zone: Asia/Shanghai

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: never

utils:
  snowflake:
    worker-id: 1
    datacenter-id: 1
